FROM barton:5000/spectrumauto
COPY triangle.tap /home/spectrum/tapes/triangle.tap
COPY string.tap /home/spectrum/tapes/string.tap
COPY infinipi.tap /home/spectrum/tapes/infinipi.tap
COPY combined.tap /home/spectrum/tapes/combined.tap
